name: $(Year:yyyy).$(Month).$(Date:dd)$(Rev:.r)

trigger: none
    
parameters:
- name: repoName
  type: string
  default: "IST.GLB.GLB.INFRASTRUCTURE"
  values: [ "IST.GLB.GLB.INFRASTRUCTURE" , "IST.GLB.GLB.DATA_ASSET_BUILDER_ADF", "IST.GLB.GLB.DATA_ASSET_BUILDER_NOTEBOOKS", "IST.GLB.GLB.GDS_DATAPLATFORM.DATA_ASSET_REGISTRY", "IST.GLB.GLB.GDS_DATAPLATFORM.DATA_ASSET_BUILDER", "IST.GLB.GLB.GDS_OBSERVABILITY_UTILITIES" ]
- name: projectName
  type: string
  default: "IST.GLB.GLB.GDS_DATAPLATFORM"
- name: branchName
  type: string
  default: "main"

variables:
- name: projectName
  value: "IST.GLB.GLB.GDS_DATAPLATFORM"
- name: repoName
  value: "IST.GLB.GLB.DATA_ASSET_BUILDER_ADF"

jobs:
  - job: create_git_tag
    displayName: "Create tag for repository ${{ parameters.repoName }}"
    steps:
      - checkout: none
      - task: PowerShell@2
        displayName: "Clone the repository"
        inputs:
          targetType: 'inline'
          script: |
           git -c http.extraheader="AUTHORIZATION: Bearer $(System.AccessToken)" clone --branch "${{parameters.branchName}}" "https://sdxcloud@dev.azure.com/sdxcloud/IST.GLB.GLB.GDS_DATAPLATFORM/_git/${{parameters.repoName}}" "$(Build.SourcesDirectory)"
           ls "$(Build.SourcesDirectory)"
      - template: /pipelines/steps/set-semantic-version.yml
      - task: PowerShell@2
        displayName: "Create Git Tag on Repository using SemVer"
        inputs: 
          targetType: 'inline'
          script: |
            $env:AZURE_DEVOPS_EXT_PAT = '$(System.AccessToken)'
            $objectId=$(git rev-parse HEAD)
            az repos ref create --name "refs/tags/$(SemVer)" `
                                --object-id $objectID `
                                --project "${{parameters.projectName}}" `
                                --repository "${{parameters.repoName}}"
