name: $(Year:yyyy).$(Month).$(Date:dd)$(Rev:.r)

trigger: none

resources:
  repositories:
    - repository: code_wiki
      type: git
      name: IST.GLB.GLB.GDS_DATAPLATFORM_FORK
      ref: main
      trigger:
        branches:
          include:
            - main

jobs:
  - job: create_git_tag
    displayName: "Synchronize wikis"
    steps:
      - checkout: code_wiki
        persistCredentials: true
        fetchDepth: 0
      - task: PowerShell@2
        displayName: "Synchronize code wiki with project wiki"
        inputs:
          targetType: 'inline'
          script: |
           git config --global user.email "sync@sodexo.com"
           git config --global user.name "Wiki Sync"
           # set git path context
           cd $(Build.SourcesDirectory)

           # add project wiki remote for sync
           git remote add wiki https://$(System.AccessToken)@sdxcloud.visualstudio.com/IST.GLB.GLB.GDS_DATAPLATFORM/_git/IST.GLB.GLB.GDS_DATAPLATFORM.wiki
           
           # fetch all available branches
           git fetch --all
           
           # create main branch from code wiki locally
           git checkout -b main origin/main
           
           # create main branch from project wiki locally
           git checkout -b wikiMaster wiki/wikiMaster
           
           # rebase project wiki with latest code wiki changes
           git rebase main
           
           # sync project wiki
           git push wiki
